# Generated by Django 2.2.4 on 2021-05-24 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dojo',
            new_name='User',
        ),
    ]
